<?php
$title = 'Delete Category';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete '<?= $this->escapeHtml($category->name); ?>''?
</p>
<?php
$url = $this->url('category', ['action' => 'delete', 'id' => $this->id]);
?>
<form action="<?= $url; ?>" method="post">
	<div>
		<input type="hidden" name="id" value="<?= (int) $category->id; ?>" />
		<input type="submit" name="del" value="Yes" />
		<input type="submit" name="del" value="No" />
	</div>
</form>