<?php
$title = 'Categories';
$this->headTitle($title);
?>
<h1>
	<?= $this->escapeHtml($title); ?>
	<a class="pull-right btn btn-lg btn-success" href="<?= $this->url('category', ['action' => 'add']); ?>">Add new Category</a>
</h1>

<table class="table table-striped">
	<thead>
		<tr>
			<th>Name</th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	<?php foreach ($categories as $category) : ?>
		<tr>
			<td><?= $this->escapeHtml($category->name); ?></td>
			<td class="text-right">
				<a class="btn btn-sm btn-warning" href="<?= $this->url('category', ['action' => 'edit', 'id' => $category->id]); ?>">Edit</a>
				<a class="btn btn-sm btn-danger" href="<?= $this->url('category', ['action' => 'delete', 'id' => $category->id]); ?>">Delete</a>
			</td>
		</tr>
	<?php endforeach; ?>
</table>